Docket/urls.py
from django.contrib import admin
from django.urls import path, include

import calender.views as views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.make_welcome, name='index'),
    path('event/<int:id>', views.update_event, name='update_event'),
    path('event/new', views.new_event, name='new_event'),
    path('event/delete/<int:id>', views.delete_event, name='delete_event'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/new', views.new_user, name='new_user'),
    path('shifts/', views.make_shifts, name='view_shifts'),
    path('conflicts/', views.update_conflict, name='update_conflict'),
    path('conflicts/rc/<int:id>', views.delete_conflict_rc, name='delete_conflict_rc'),
    path('conflicts/c/<int:id>', views.delete_conflict_c, name='delete_conflict_c'),
]

ShiftScheduler/urls.py
from django.contrib import admin
from django.urls import path, include

import calender.views as views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.make_welcome, name='index'),
    path('event/<int:id>', views.update_event, name='update_event'),
    path('event/new', views.new_event, name='new_event'),
    path('event/delete/<int:id>', views.delete_event, name='delete_event'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/new', views.new_user, name='new_user'),
    path('shifts/', views.make_shifts, name='view_shifts'),
    path('conflicts/', views.update_conflict, name='update_conflict'),
    path('conflicts/rc/<int:id>', views.delete_conflict_rc, name='delete_conflict_rc'),
    path('conflicts/c/<int:id>', views.delete_conflict_c, name='delete_conflict_c'),
]

calender/models.py
from django.db import models
from django.contrib.auth.models import User

from datetime import datetime, time, date

def _timenow():
    return datetime.time(datetime.now())

# Create your models here.
class Event(models.Model):
    title = models.CharField(max_length=100)
    start_time = models.DateTimeField(default=datetime.now)
    end_time = models.DateTimeField(default=datetime.now)

# A block of time which the employee can't be scheduled for
class Conflict(models.Model):
    employee = models.ForeignKey(User, on_delete=models.CASCADE)
    start_time = models.DateTimeField(default=datetime.now)
    end_time = models.DateTimeField(default=datetime.now)

    def is_conflict(obj, date: datetime) -> bool:
        st: datetime = obj.start_time
        et: datetime = obj.end_time
        return not st < date < et

class RepeatedConflict(models.Model):
    employee = models.ForeignKey(User, on_delete=models.CASCADE)
    day = models.CharField(max_length=10)
    start_time = models.TimeField(default=_timenow)
    end_time = models.TimeField(default=_timenow)

    def is_conflict(obj, date: datetime) -> bool:
        st: time = obj.start_time
        et: time = obj.end_time

        totime = lambda d: datetime.time(d)
        return date.strftime("%A") == obj.day and not st < totime(date) < et

# Keeps a mapping of employees to events
class EventToEmployee(models.Model):
    employee = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

calender/forms.py
from datetime import datetime
from django import forms

from django.contrib import admin
from django.contrib.auth.models import User
from django.contrib.auth.admin import UserAdmin
from django.contrib.auth.forms import UserCreationForm

from .models import Event, Conflict

DAYS = (
    ('Sunday', 'Sunday'),
    ('Monday', 'Monday'),
    ('Tuesday', 'Tuesday'),
    ('Wednesday', 'Wednesday'),
    ('Thursday', 'Thursday'),
    ('Friday', 'Friday'),
    ('Saturday', 'Saturday'),
)

class EventForm(forms.ModelForm):
    start_time = forms.DateTimeField(
        input_formats=['%m/%d/%Y %I:%M %p'],
        widget=forms.widgets.DateTimeInput(
            format="%m/%d/%Y %I:%M %p",
            attrs={'class': 'form-control datetimepicker-input',
                    'data-target': '#datetimepicker1',
                    'placeholder':"MM/DD/YY HH:MM(AP)"}))
    end_time = forms.DateTimeField(
        input_formats=['%m/%d/%Y %I:%M %p'],
        widget=forms.widgets.DateTimeInput(
            format="%m/%d/%Y %I:%M %p",
            attrs={'class': 'form-control datetimepicker-input',
                    'data-target': '#datetimepicker2',
                    'placeholder':"MM/DD/YY HH:MM(AP)"}))
    class Meta:
        model = Event
        fields = "__all__"

class ScheduleForm(forms.Form):
    employees = forms.ModelMultipleChoiceField(
        queryset=User.objects.filter(is_superuser=False))

class ConflictForm(forms.Form):
    repeated = forms.BooleanField(
        required=False)
    repeated_days = forms.MultipleChoiceField(
        required=False,
        choices=DAYS)
    day = forms.DateTimeField(
        input_formats=['%m/%d/%Y'],
        initial=datetime.now,
        widget=forms.widgets.DateInput(
            format="%m/%d/%Y",
            attrs={'class': 'form-control datetimepicker-input',
                    'data-target': '#datetimepicker1',
                    'placeholder':"MM/DD/YY"}))
    start_time = forms.DateTimeField(
        required=True,
        input_formats=['%I:%M %p'],
        widget=forms.widgets.TimeInput(
            format="%I:%M %p",
            attrs={'class': 'form-control datetimepicker-input',
                    'data-target': '#datetimepicker2',
                    'placeholder':"HH:MM(AP)"}))
    end_time = forms.DateTimeField(
        required=True,
        input_formats=['%I:%M %p'],
        widget=forms.widgets.TimeInput(
            format="%I:%M %p",
            attrs={'class': 'form-control datetimepicker-input',
                    'data-target': '#datetimepicker3',
                    'placeholder':"HH:MM(AP)"}))
    # class Meta:
    #     model = Conflict
    #     fields = ('start_time', 'end_time')
    #     exclude = ('employee')

# # https://stackoverflow.com/a/28897968
class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name' , 'last_name')

class UserAdmin(UserAdmin):
    add_form = UserCreateForm
    prepopulated_fields = {'username': ('first_name' , 'last_name')}

    # https://stackoverflow.com/a/53237541
    add_fieldsets = (
        (None, {
            'classes': ('wide',),
            'fields': ('first_name', 'last_name', 'username', 'password1', 'password2', ),
        }),
    )

# Re-register user models to add new fields
admin.site.unregister(User)
admin.site.register(User, UserAdmin)

calender/views.py
from django.contrib.auth.models import AnonymousUser
from django.db.models.manager import BaseManager
from django.db.models.query import QuerySet
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import render, redirect

from django.contrib.auth import login, get_user
from django.contrib.auth.forms import UserChangeForm

from datetime import datetime, timedelta, time, date

from .models import Event, EventToEmployee, RepeatedConflict, User, Conflict
from .forms import EventForm, UserCreateForm, ConflictForm, ScheduleForm

# Create your views here.
def make_welcome(request: HttpRequest) -> HttpResponse:
    user = get_user(request)
    if user.username != "":
        today = datetime.today()
        tomorrow = today + timedelta(days=1)
        events = Event.objects.filter(
            start_time__gte=datetime.date(today),
            start_time__lt=datetime.date(tomorrow))
    else:
        events = Event.objects.none()

    employees = []
    for event in events:
        try:
            matches = EventToEmployee.objects.filter(event=event) #!
            names = []
            for match in matches:
                names.append(User.objects.get(id=match.employee.id).first_name)
            employees.append("".join([n+', ' for n in names]))
        except EventToEmployee.DoesNotExist:
            employees.append('NEEDS SCHEDULING')

    context = { 'user': user, 'events': events, 'employees': employees }
    return render(request, 'calender/welcome.html', context)

def make_shifts(request: HttpRequest) -> HttpResponse:
    user = get_user(request)
    if user.username == "":
        context = { 'user': user, 'events': Event.objects.none() }
        return render(request, 'calender/shifts.html', context)

    events = Event.objects.all()
    employees = []
    for event in events:
        try:
            matches = EventToEmployee.objects.filter(event=event) #!
            names = []
            for match in matches:
                names.append(User.objects.get(id=match.employee.id).first_name)
            employees.append("".join([n+', ' for n in names]))
        except EventToEmployee.DoesNotExist:
            employees.append('NEEDS SCHEDULING')

    context = { 'user': user, 'events': events, 'employees': employees }
    return render(request, 'calender/shifts.html', context)

def new_event(request: HttpRequest) -> HttpResponse:
    eventform = EventForm(request.POST or None)

    if request.method == 'POST':
        if eventform.is_valid():
            eventform.save(commit=True)
            return redirect('index')

    context = { 'user': get_user(request), 'event_form': eventform }
    return render(request, 'calender/new_event.html', context)

def delete_event(request: HttpRequest, id: int) -> HttpResponse:
    event = Event.objects.get(id=id)
    event.delete()
    return redirect('view_shifts')

def update_event(request: HttpRequest, id: int) -> HttpResponse:
    user = get_user(request)
    if user.username == "":
        return redirect('index')

    event = Event.objects.get(id=id)
    eventform = EventForm(request.POST or None, instance=event)
    scheduleform = ScheduleForm(request.POST or None)

    if request.method == 'POST':
        if eventform.is_valid():
            eventform.save(commit=True)
        if scheduleform.is_valid():
            data = scheduleform.cleaned_data
            etime = event.start_time
            # Clear the list before replacing it
            EventToEmployee.objects.filter(event=event).delete()
            for employee in data['employees']:
                if not EventToEmployee.objects.filter(employee=employee).exists():
                    conflicts = Conflict.objects.filter(employee=employee)
                    repeat_conflicts = RepeatedConflict.objects.filter(employee=employee)

                    has_conflict = False
                    for conflict in conflicts:
                        if Conflict.is_conflict(conflict, etime):
                            has_conflict = True
                            break
                    if not has_conflict:
                        for conflict in repeat_conflicts:
                            if RepeatedConflict.is_conflict(conflict, etime):
                                has_conflict = True
                                break
                    if not has_conflict:
                        EventToEmployee.objects.create(employee=employee, event=event)
        return redirect('view_shifts')

    context = { 'user': user, 'event_form': eventform, 'schedule_form': scheduleform }
    return render(request, 'calender/update_event.html', context)

def update_conflict(request: HttpRequest) -> HttpResponse:
    user = get_user(request)
    if user.username == "":
        return redirect('index')

    conflictform = ConflictForm(request.POST or None)
    if request.method == 'POST':
        if conflictform.is_valid():
            data = conflictform.cleaned_data
            if data['repeated']:
                for day in data['repeated_days']:
                    repc = RepeatedConflict()
                    start_time: datetime = data['start_time']
                    end_time: datetime = data['end_time']
                    repc.employee = user
                    repc.day = day
                    repc.start_time = start_time
                    repc.end_time = end_time
                    repc.save()
            else:
                conflict = Conflict()
                day: date = datetime.date(data['day'])
                start_time: time = datetime.time(data['start_time'])
                end_time: time = datetime.time(data['end_time'])
                conflict.employee = user
                conflict.start_time = datetime.combine(day, start_time)
                conflict.end_time = datetime.combine(day, end_time)
                conflict.save()
            conflictform = ConflictForm()

    conflicts = Conflict.objects.filter(employee=user)
    rc = RepeatedConflict.objects.filter(employee=user)

    context = { 'user': user, 'repeat_conflicts': rc, 'conflicts': conflicts, 'conflict_form': conflictform }
    return render(request, 'calender/update_conflict.html', context)

def delete_conflict_rc(request: HttpRequest, id: int) -> HttpResponse:
    RepeatedConflict.objects.get(id=id).delete()
    return redirect('update_conflict')

def delete_conflict_c(request: HttpRequest, id: int) -> HttpResponse:
    Conflict.objects.get(id=id).delete()
    return redirect('update_conflict')

def new_user(request: HttpRequest) -> HttpResponse:
    userform = UserCreateForm(request.POST or None)

    if request.method == 'POST':
        if userform.is_valid():
            newuser = userform.save(commit=True)
            login(request, newuser)
            return redirect('index')

    context = { 'user': get_user(request), 'user_form': userform }
    return render(request, 'calender/new_user.html', context)

def make_user(request: HttpRequest) -> HttpResponse:
    user = get_user(request)
    if user.username == "":
        return redirect('new_user')

    userform = UserChangeForm(request.POST or None, instance=user)
    if request.method == 'POST':
        userform.save(commit=True)
        return redirect('index')

    context = { 'user': user, 'user_form': userform }
    return render(request, 'calender/modify_user.html', context)

templates/calender/calender.html
{% extends 'base.html' %}

templates/calender/modify_user.html
{% extends 'base-form.html' %}

{% block head %}
<title>Shifty Scheduler</title>
{% endblock %}

{% block form %}
<div class="col-lg-6 align-items-center my-auto g-2">
    <div class="display-2">{{ user.first_name }} {{ user.last_name }}</div>
    <div class="display-6 lead">{{ user.username }}</div>
</div>
<form class="col-lg-6 justify-content-center g-2" method="post">
    {% csrf_token %}
    {% load crispy_forms_tags %}
    {{ user_form|crispy }}
    <button type="submit" class="my-2 btn btn-success">Save User</button>
</form>
{% endblock %}

templates/calender/new_event.html
{% extends 'base-form.html' %}

{% block head %}
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<!-- Moment.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js"
    integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

<!-- Tempus Dominus Bootstrap 4 -->
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css"
    integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"
    integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

<title>New Event</title>
{% endblock %}

{% block form %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <form class="form" method="post">
            <!-- https://simpleisbetterthancomplex.com/tutorial/2019/01/03/how-to-use-date-picker-with-django.html -->
            {% csrf_token %}
            {{ event_form.errors }}
            <div class="row justify-content-center my-3">
                <label for="title">{{ event_form.title.label }}</label>
                <div class="col-4">
                    {{ event_form.title }}
                </div>
            </div>
            <div class="row g-3">
                <div class="col-12">
                    <label for="start_time">{{ event_form.start_time.label }}</label>
                    <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                        {{ event_form.start_time }}
                        <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <label for="end_time">{{ event_form.end_time.label }}</label>
                    <div class="input-group date" id="datetimepicker2" data-target-input="nearest">
                        {{ event_form.end_time }}
                        <div class="input-group-append" data-target="#datetimepicker2" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                </div>
            </div>


            <button type="submit" class=" my-2 btn btn-success">Add Event</button>

            <script>
                $(function () {
                    $("#datetimepicker1").datetimepicker({
                        format: 'MM/DD/YYYY hh:mm A',
                    });
                });

                $(function () {
                    $("#datetimepicker2").datetimepicker({
                        format: 'MM/DD/YYYY hh:mm A',
                    });
                });
            </script>
        </form>
    </div>
</div>

{% endblock %}

templates/calender/new_user.html
{% extends 'base-form.html' %}
{% load crispy_forms_tags %}

{% block head %}
<title>Add a new user</title>
{% endblock %}

{% block form %}
<form class="form justify-content-center g-2" method="post">
    {% csrf_token %}
    {{ user_form|crispy }}
    <button type="submit" class="my-2 btn btn-success">Add User</button>
</form>
{% endblock %}

templates/calender/shifts.html
{% extends 'base.html' %}
{% load index %}

{% block head %}
<title>Shifty Scheduler</title>
{% endblock %}

{% block body %}
<div class="container-fluid justify-content-center p-2">
    <div class="row text-center m-1 b-1 shadow p-2 mb-5 bg-white rounded border">
        <h3 class="display-3 text-center">All Shifts</h3>
        {% for event in events %}
        <div class="col-lg-4 fs-4">{{ event.title }}</div>
        <div class="col-lg-4 fs-4">
            <p>{{ event.start_time }} - {{ event.end_time }}</p>
            {{ employees|index:forloop.counter0 }}
        </div>
        <div class="col-lg-4">
            <a class="btn btn-primary mx-1" href="{% url 'update_event' event.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'delete_event' event.id %}">Delete</a>
        </div>
        {% empty %}
        <h3 class="display-6 text-center">Either there are no events planned, or you're not logged in.</h3>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/calender/update_conflict.html
{% extends 'base-form.html' %}
{% load crispy_forms_tags %}
{% load totime %}

{% block head %}
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<!-- Moment.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js"
    integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

<!-- Tempus Dominus Bootstrap 4 -->
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css"
    integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"
    integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

<title>Shifty Scheduler</title>
{% endblock %}

{% block form %}
<div class="col-lg-6 my-auto g-2">
    <div class="display-2">{{ user.first_name }} {{ user.last_name }}</div>
    <form class="align-items-center text-center g-2 my-2" method="post">
        {% csrf_token %}
        {{ conflict_form.errors }}
        <div class="col-12">
            {{ conflict_form.repeated.label_tag }}
            {{ conflict_form.repeated }}
        </div>
        <div class="col-12" id="repeated_days_group" hidden="true">
            {{ conflict_form.repeated_days.label_tag }}
            {{ conflict_form.repeated_days }}
        </div>
        <div class="col-12" id="day_group">
            {{ conflict_form.day.label_tag }}
            <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                {{ conflict_form.day }}
                <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
            </div>
        </div>
        <div class="col-12">
            {{ conflict_form.start_time.label_tag }}
            <div class="input-group date" id="datetimepicker2" data-target-input="nearest">
                {{ conflict_form.start_time }}
                <div class="input-group-append" data-target="#datetimepicker2" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
            </div>
        </div>
        <div class="col-12">
            {{ conflict_form.end_time.label_tag }}
            <div class="input-group date" id="datetimepicker3" data-target-input="nearest">
                {{ conflict_form.end_time }}
                <div class="input-group-append" data-target="#datetimepicker3" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
            </div>
        </div>
        <button type="submit" class="my-2 btn btn-success">Add Conflict</button>

        <script>
            $('#id_repeated').click((event) => {
                $('#repeated_days_group').prop('hidden', !($('#id_repeated').prop('checked')));
                $('#day_group').prop('hidden', $('#id_repeated').prop('checked'));
            });

            $(function () {
                $("#datetimepicker1").datetimepicker({
                    format: 'MM/DD/YYYY',
                });
            });

            $(function () {
                $("#datetimepicker2").datetimepicker({
                    format: 'hh:mm A',
                });
            });

            $(function () {
                $("#datetimepicker3").datetimepicker({
                    format: 'hh:mm A',
                });
            });
        </script>
    </form>
</div>
<div class="col-lg-6 g-2">
    <div class="row">
        <div class="display-2 text-center">Current Conflicts</div>
    </div>
    <div class="row">
        <table>
            <thead>
                <tr>
                    <th>Day</th>
                    <th>Time</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for rc in repeat_conflicts %}
                <tr>
                    <td>{{ rc.day }}</td>
                    <td>{{ rc.start_time }} - {{ rc.end_time }}</td>
                    <td>
                        <a class="btn btn-danger" href="{% url 'delete_conflict_rc' rc.id %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
                {% for c in conflicts %}
                <tr>
                    <td>{{ c.start_time|totime:1 }}</td>
                    <td>{{ c.start_time|totime:0 }} - {{ c.end_time|totime:0 }}</td>
                    <td>
                        <a class="btn btn-danger" href="{% url 'delete_conflict_c' c.id %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/calender/update_event.html
{% extends 'base-form.html' %}
{% load crispy_forms_tags %}

{% block head %}
<title>Update Event</title>
{% endblock %}

{% block form %}
<form class="form justify-content-center g-2" method="post">
    {% csrf_token %}
    {{ event_form|crispy }}
    <button type="submit" class=" my-2 btn btn-success">Update Event</button>
</form>

<form class="form justify-content-center g-2" method="post">
    {% csrf_token %}
    {{ schedule_form|crispy }}
    <button type="submit" class=" my-2 btn btn-success">Add To Schedule</button>
</form>
{% endblock %}

templates/calender/welcome.html
{% extends 'base.html' %}
{% load index %}

{% block head %}
<title>Shifty Scheduler</title>
{% endblock %}

{% block body %}
<div class="container-lg justify-content-center p-2">
    <div class="row m-1">
        <h1 class="display-1 text-center">Welcome!</h1>
    </div>
    <div class="row m-1 b-1 shadow p-2 mb-5 bg-white rounded border">
        <h3 class="display-6 text-center">Today's shifts</h3>
        {% for event in events %}
        <div class="col-lg-6 text-end fs-5">{{ event.title }}: {{ event.start_time }}</div>
        <div class="col-lg-6 fs-5">
            {{ employees|index:forloop.counter0 }}
        </div>
        {% empty %}
        <h3 class="display-6 text-center">Either there are no events planned, or you're not logged in.</h3>
        {% endfor %}
    </div>
</div>
{% endblock %}